### PR TITLE
added an extension to IWebHost

### PR DESCRIPTION
**Pull request by Trapov**
Added an extension as a different project.

In the first attempt i was trying to divide your project in to small pieces so i would not need the whole package, but i coulnd't do it so well(u still can find my branch tho), so i ended up on this. 

Will update and edit everyting as you say.

Issue -> https://github.com/dasMulli/dotnet-win32-service/issues/57

### CODE REVIEW

**Comment by dasMulli** [comment]
I don't really like the idea of adding a dependency on either .Hosting or .Hosting.Abstractions to the main package since it adds quite a lot of dlls to non-asp.net core projects.
Additionally, there will likely be updates to the hosting / abstractions that don't need to cause updates to the main service functionality. E.g. there will be a new hosting model in 2.1 (`IHost` vs `IWebHost`) and I still want the main package to work in both 2.0 and 2.1.

What do you think about making this its own nuget package? (I could do so after merging).

**Comment by Trapov** [comment]
@dasMulli ya, i was thinking the same actually. but this feature doesn't really require the whole project, so it feels kinda bloated with not needed dependencies. It would be greate if you could breake your project into different layers and then it would be really small and lightweight :)

but yes, i will update my PR and make this extension as a different project for now.

**Comment by Trapov** [comment]
@dasMulli wait i haven't updated my PR still, i thought you wanted it as a separate project.

**Comment by dasMulli** [comment]
I'm on that already 😉

**Comment by Trapov** [comment]
@dasMulli oh, ok, great then. feels like i dropped something that i had to do on you tho :)

**Comment by dasMulli** [comment]
see https://github.com/dasMulli/dotnet-win32-service/pull/59

**Pull request merged**
